# Generated by Django 4.2 on 2026-04-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
